# Generated by Django 4.2.11 on 2025-09-15 22:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=999, primary_key=True, serialize=False),
        ),
    ]
