"""
Django settings for conf project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

load_dotenv()
BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = os.getenv("SECRET_KEY", "insecure-secret-key")
DEBUG = os.getenv("DEBUG", True)

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://72.60.210.63",
    "http://alhameedcomputers.com",
    "https://alhameedcomputers.com",
]

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "localhost:3000",
    "72.60.210.63",
    "alhameedcomputers.com",
    "admin.alhameedcomputers.com",
]

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "production_db",
        "USER": "unityalgo",
        "PASSWORD": "123",
        "HOST": "localhost",
        "PORT": "5432",
    }
}
STATIC_URL = "static/"
STATIC_ROOT = "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


UNFOLD_ADMIN_CONFIG = {
    "SITE_TITLE": "UnityAlgo Admin",
    "SITE_HEADER": "Welcome to UnityAlgo Admin",
    "SITE_URL": "/",
    "THEME": "dark",
}
