# Generated by Django 5.2.1 on 2025-09-03 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_cart_currency_uom_category_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'customer')},
        ),
        migrations.AlterField(
            model_name='productreview',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ecommerce.customer'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='order_item',
        ),
    ]
