# Generated by Django 5.1.5 on 2025-10-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_paymentmethod_shippingrule_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_listing_item',
            field=models.BooleanField(default=False),
        ),
    ]
