# Generated by Django 5.2.4 on 2025-11-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_product_meta_description_product_meta_keywords_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='qty',
        ),
    ]
