# Generated by Django 5.2.4 on 2025-11-08 00:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_rename_quantity_cartitem_qty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingrule',
            options={'ordering': ['name', 'is_active']},
        ),
        migrations.RemoveField(
            model_name='shippingrule',
            name='free_shipping_threshold',
        ),
        migrations.RemoveField(
            model_name='shippingrule',
            name='max_order_amount',
        ),
        migrations.RemoveField(
            model_name='shippingrule',
            name='min_order_amount',
        ),
        migrations.AddField(
            model_name='shippingrule',
            name='based_on',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('weight', 'Weight'), ('price', 'Price')], default='fixed', max_length=50),
        ),
        migrations.AddField(
            model_name='shippingrule',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),

        migrations.CreateModel(
            name='ShippingRuleCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='ecommerce.shippingrule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
