# Generated by Django 5.2.1 on 2025-11-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_paymentmethod_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
